using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Documenter
{
    public class PdfReport
    {
        public static void Generate(string filePath, string content)
        {
            QuestPDF.Settings.License = LicenseType.Community;

            Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(2, Unit.Centimetre);
                    page.PageColor(Colors.White);

                    // FIX: Force English Text Direction (Fixes reversed text issue)
                    page.ContentFromLeftToRight();

                    page.DefaultTextStyle(x => x.FontSize(10).FontColor(Colors.Black).FontFamily(Fonts.SegoeUI));

                    // --- HEADER ---
                    page.Header()
                        .Text("Project Architecture Documentation")
                        .Bold().FontSize(20).FontColor(Colors.Blue.Darken3).AlignCenter();

                    // --- CONTENT ---
                    page.Content().PaddingVertical(1, Unit.Centimetre).Column(col =>
                    {
                        foreach (var line in content.Split('\n'))
                        {
                            var cleanLine = line.Trim();

                            // 1. File Title (## 📂 File: Name)
                            if (cleanLine.StartsWith("## 📂"))
                            {
                                col.Item().PageBreak(); // New page for every file
                                col.Item().PaddingTop(10).Text(cleanLine.Replace("#", "").Trim())
                                   .FontSize(16).Bold().FontColor(Colors.Blue.Darken2);
                                col.Item().LineHorizontal(1).LineColor(Colors.Grey.Lighten2);
                            }
                            // 2. Section Headers (### 🏗️ Structure)
                            else if (cleanLine.StartsWith("###"))
                            {
                                col.Item().PaddingTop(15).PaddingBottom(5)
                                   .Text(cleanLine.Replace("#", "").Trim())
                                   .FontSize(12).Bold().FontColor(Colors.Black);
                            }
                            // 3. Table Rows (Simple formatting for the variables table)
                            else if (cleanLine.StartsWith("|"))
                            {
                                col.Item().Background(Colors.Grey.Lighten4).Padding(2)
                                   .Text(cleanLine).FontFamily(Fonts.Consolas).FontSize(9);
                            }
                            // 4. Diagram Code (Hide the raw mermaid block markers)
                            else if (cleanLine.StartsWith("```")) { /* Hide markers */ }

                            // 5. Normal Text
                            else
                            {
                                if (!string.IsNullOrWhiteSpace(cleanLine))
                                    col.Item().Text(cleanLine);
                            }
                        }
                    });

                    // --- FOOTER ---
                    page.Footer().AlignCenter().Text(x =>
                    {
                        x.Span("Generated by AI Documenter | Page ");
                        x.CurrentPageNumber();
                    });
                });
            })
            .GeneratePdf(filePath);
        }
    }
}