using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Documenter
{
    public class PdfReport
    {
        public static void Generate(string filePath, string content)
        {
            QuestPDF.Settings.License = LicenseType.Community;

            Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(2, Unit.Centimetre);
                    page.PageColor(Colors.White);
                    page.DefaultTextStyle(x => x.FontSize(11).FontColor(Colors.Grey.Darken3));

                    // --- HEADER ---
                    page.Header()
                        .Text("Project Documentation")
                        .SemiBold().FontSize(26).FontColor(Colors.Blue.Darken2).LetterSpacing(-1).AlignCenter();

                    // --- CONTENT LOOP ---
                    page.Content().PaddingVertical(1, Unit.Centimetre).Column(col =>
                    {
                        foreach (var line in content.Split('\n'))
                        {
                            var cleanLine = line.Trim();

                            // 1. Big File Headers (## 📄 FileName)
                            if (cleanLine.StartsWith("##"))
                            {
                                col.Item().PaddingTop(25).PaddingBottom(5)
                                   .Text(cleanLine.Replace("#", "").Trim())
                                   .FontSize(18).Bold().FontColor(Colors.Teal.Darken1);

                                // Add a decorative line under the header
                                col.Item().LineHorizontal(2).LineColor(Colors.Teal.Lighten4);
                            }
                            // 2. Sub-Headers (### 💡 What is this?)
                            else if (cleanLine.StartsWith("###"))
                            {
                                col.Item().PaddingTop(15).PaddingBottom(5)
                                   .Text(cleanLine.Replace("#", "").Trim())
                                   .FontSize(14).SemiBold().FontColor(Colors.Orange.Darken2);
                            }
                            // 3. Bold Bullet Points (* 🛡️ Feature:)
                            else if (cleanLine.StartsWith("*") || cleanLine.StartsWith("-"))
                            {
                                var text = cleanLine.TrimStart('*', '-', ' ');
                                col.Item().PaddingLeft(15).PaddingBottom(2).Row(row =>
                                {
                                    row.AutoItem().Text("• ").FontColor(Colors.Grey.Medium);
                                    row.RelativeItem().Text(text);
                                });
                            }
                            // 4. Skip Code Block Markers
                            else if (cleanLine.StartsWith("```")) { /* Skip */ }

                            // 5. Normal Text
                            else
                            {
                                if (!string.IsNullOrWhiteSpace(cleanLine))
                                    col.Item().PaddingBottom(2).Text(cleanLine);
                            }
                        }
                    });

                    page.Footer().AlignCenter().Text(x =>
                    {
                        x.Span("Generated by AI Documenter | Page ").FontSize(9).FontColor(Colors.Grey.Medium);
                        x.CurrentPageNumber();
                    });
                });
            })
            .GeneratePdf(filePath);
        }
    }
}